services:
  proxy:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    depends_on:
      app:
        condition: service_healthy
      
  app:
    image: ${APP_IMAGE}
    expose: 
      - "3000"
    networks:
      - frontend
      - backend
    environment:
      DB_URI: "mongodb://db:27017"
    healthcheck:
      test: "curl -f localhost:3000"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: mongo:6.0.4
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: data
    networks:
      - backend
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s

networks:
  frontend:
  backend: