services:
  # proxy:
  #   image: nginx:1.23.3
  #   ports:
  #     - "80:80"
  #   volumes: 
  #     - ./nginx/my.conf:/etc/nginx/conf.d/default.conf
  #     - ./app/project/static:/usr/share/nginx/html/static
  #   networks:
  #     - frontend
  #   depends_on:
  #     app:
  #       condition: service_healthy
      
  app:
    build: .
    ports: 
      - 3000:3000
    networks:
      - frontend
      - backend
    environment:
      DB_URI: "mongodb://db:27017"
    # healthcheck:
    #   test: "curl -f localhost:3000"
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20
    #   start_period: 30s
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: mongo:6.0.4
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: data
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 10
      start_period: 10s

networks:
  frontend:
  backend: