name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
 id-token: write
 contents: write
 
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
   # - name: Build Docker image
    #  run: docker build . --file Dockerfile --tag app
      
    #- name: E2E test
     # run: |
      #  export APP_IMAGE=app
       # docker compose up -d
        #chmod +x ./tests/e2e-test.sh
        #./tests/e2e-test.sh localhost:80
    
    - name: Version
      if: startsWith(github.ref, 'refs/heads/main')
      id: version
      uses: PaulHatch/semantic-version@v5.0.3
      with:
        tag_prefix: ""
        version_format: "${major}.${minor}.${patch}"
    
    #- name: Configure AWS Credentials
     # if: startsWith(github.ref, 'refs/heads/main')
      #uses: aws-actions/configure-aws-credentials@v2
      #with:
       # role-to-assume: arn:aws:iam::752620938895:role/linkme-github-actions-role
        #aws-region: eu-west-3
    
    #- name: Publish image to ECR
     # if: startsWith(github.ref, 'refs/heads/main')
      #run: |
       # aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 752620938895.dkr.ecr.eu-west-3.amazonaws.com
        #docker tag app:latest 752620938895.dkr.ecr.eu-west-3.amazonaws.com/linkme:${{ steps.version.outputs.version_tag }}
        #docker push 752620938895.dkr.ecr.eu-west-3.amazonaws.com/linkme:${{ steps.version.outputs.version_tag }}
        
   # - name: Tag commit
    #  if: startsWith(github.ref, 'refs/heads/main')
     # run: |
      #  git config --global user.name ${{ secrets.GITHUB_USERNAME }}
       # git config --global user.email ${{ secrets.GITHUB_USER_EMAIL }}
        #git tag -a ${{ steps.version.outputs.version_tag }} -m "new release - version ${{ steps.version.outputs.version_tag }}"
        #git push origin ${{ steps.version.outputs.version_tag }}
      #env:
       # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
   # - name: Clone gitops repo
    #  uses: GuillaumeFalourd/clone-github-repo-action@v2
     # with:
      #  owner: RachelNaane
       # repository: linkMe-gitops
        #access-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Clone gitops repo
      uses: actions/checkout@v2
      with:
        repository: RachelNaane/linkMe-gitops
        ref: main
        
    - name: Update image version gitops repo
      run: |
        cd linkMe/
        git config --global user.email ${{ secrets.GITHUB_USER_EMAIL }}
        git config --global user.name ${{ secrets.GITHUB_USERNAME }}
        sed -i "s/tag: .*/tag: ${{ steps.version.outputs.version_tag }}/" values.yaml
        git add values.yaml
        git commit -m "by terraform - updated image tag to ${{ steps.version.outputs.version_tag }}"
      #  git push https://${{ secrets.GITHUB_TOKEN }}@github.com/RachelNaane/linkMe-gitops.git
     # env:
      #  GITOPS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{secrets.GMAIL_SMTP}}
        subject: ${{ github.job }} job of ${{ github.repository }} finished with status - ${{ job.status }} 
        to: ${{github.event.pusher.email}}
        from: Github
        body: ${{ github.job }} job in ${{ github.repository }} finished with status - ${{ job.status }}
