name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    #- name: Build Docker image
     # run: docker build . --file Dockerfile --tag app
      
    #- name: E2E test
     # run: |
      #  export APP_IMAGE=app
       # docker compose up -d
        #chmod +x ./tests/e2e-test.sh
        #./tests/e2e-test.sh localhost:80
    
    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@v5.0.3
      with:
        tag_prefix: ""
        version_format: "${major}.${minor}.${patch}"
        
    - name: Set up Git
      uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        name: RachelNaane
        email: ratash3@gmail.com
        token: '${{ secrets.TOKEN_GITHUB }}'
        global: true
        actor: RachelNaane
    
    - name: Tag commit
      run: |
        git tag -a ${{ steps.version.outputs.version_tag }} -m "new release - version ${{ steps.version.outputs.version_tag }}"
        git push origin ${{ steps.version.outputs.version_tag }}
   

